In [2]:
# Import depedencies
import pandas as pd
import numpy as np

In [3]:
# Read the CSV data and create a new dataframe

df = pd.read_csv("match_team_data.csv")

In [4]:
# Create a column to account for Wins, Losses, and Ties
# Win = 1 , Loss = 0, Tie = -1

df["home_win"] = np.where(df["home_score"] > df["away_score"], 1, np.where(df["home_score"] == df["away_score"],0,-1))

In [5]:
# Check for NaNs
df2.isna().mean().sort_values(ascending=False).head(10)

NameError: name 'df2' is not defined

In [67]:
df2["winning_name"].isna()

0       False
1       False
2       False
3       False
4       False
        ...  
2957     True
2958     True
2959     True
2960     True
2961     True
Name: winning_name, Length: 2962, dtype: bool

In [68]:
# Remove NaNs
df2 = df.drop(columns=["team_2_post_season_result","team_1_post_season_result"])

In [69]:
df3 = df2.dropna()

In [70]:
df3

boxscore            away_name away_abbr  away_score  \
0     201209050nyg       Dallas Cowboys       dal        24.0   
1     201209090chi   Indianapolis Colts       clt        21.0   
2     201209090cle  Philadelphia Eagles       phi        17.0   
3     201209090det       St. Louis Rams       ram        23.0   
4     201209090htx       Miami Dolphins       mia        10.0   
...            ...                  ...       ...         ...   
2733  202209250crd     Los Angeles Rams       ram        20.0   
2734  202209250sea      Atlanta Falcons       atl        27.0   
2735  202209250tam    Green Bay Packers       gnb        14.0   
2736  202209250den  San Francisco 49ers       sfo        10.0   
2737  202209260nyg       Dallas Cowboys       dal        23.0   

                 home_name home_abbr  home_score         winning_name  \
0          New York Giants       nyg        17.0       Dallas Cowboys   
1            Chicago Bears       chi        41.0        Chicago Bears   
2         Cleveland Browns       cle        16.0  Philadelphia Eagles   
3            Detroit Lions       det        27.0        Detroit Lions   
4           Houston Texans       htx        30.0       Houston Texans   
...                    ...       ...         ...                  ...   
2733     Arizona Cardinals       crd        12.0     Los Angeles Rams   
2734      Seattle Seahawks       sea        23.0      Atlanta Falcons   
2735  Tampa Bay Buccaneers       tam        12.0    Green Bay Packers   
2736        Denver Broncos       den        11.0       Denver Broncos   
2737       New York Giants       nyg        16.0       Dallas Cowboys   

     winning_abbr           losing_name  ... team_2_rush_yards_per_attempt  \
0             dal       New York Giants  ...                           4.7   
1             chi    Indianapolis Colts  ...                           4.0   
2             phi      Cleveland Browns  ...                           4.4   
3             det        St. Louis Rams  ...                           3.4   
4             htx        Miami Dolphins  ...                           3.3   
...           ...                   ...  ...                           ...   
2733          ram     Arizona Cardinals  ...                           3.4   
2734          atl      Seattle Seahawks  ...                           4.9   
2735          gnb  Tampa Bay Buccaneers  ...                           4.7   
2736          den   San Francisco 49ers  ...                           4.5   
2737          dal       New York Giants  ...                           4.7   

      team_2_simple_rating_system  team_2_strength_of_schedule  \
0                            -4.2                         -2.2   
1                            -4.8                          2.2   
2                            38.9                         26.9   
3                            -9.0                         -6.0   
4                            12.4                          6.1   
...                           ...                          ...   
2733                         -9.0                         -6.0   
2734                        -11.3                        -10.9   
2735                         12.5                         11.5   
2736                         -4.8                         -8.2   
2737                         -4.2                         -2.2   

     team_2_turnovers team_2_win_percentage  team_2_wins  team_2_yards  \
0                   2                 0.667            2           972   
1                   6                 0.500            1           994   
2                   1                 1.000            3          1341   
3                   7                 0.667            2           919   
4                   2                 1.000            3          1066   
...               ...                   ...          ...           ...   
2733                7                 0.667            2           919   
2734                7         

In [71]:
# Check for categorical data

df3.dtypes.sort_values().tail(15)

team_1_points_contributed_by_offense    float64
away_name                                object
away_abbr                                object
home_name                                object
home_abbr                                object
team_2_abbreviation                      object
losing_name                              object
winning_abbr                             object
losing_abbr                              object
teams                                    object
team_1_abbreviation                      object
team_2_name                              object
team_1_name                              object
winning_name                             object
boxscore                                 object
dtype: object

In [72]:
# Remove categorical data

df3.drop(columns=["away_name","away_abbr","home_name","home_abbr","team_2_abbreviation","losing_name","winning_abbr","losing_abbr","teams","team_1_abbreviation","team_2_name","team_1_name","winning_name","boxscore"], inplace=True)

C:\Users\dariu\AppData\Local\Temp\ipykernel_20400\1997902423.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.drop(columns=["away_name","away_abbr","home_name","home_abbr","team_2_abbreviation","losing_name","winning_abbr","losing_abbr","teams","team_1_abbreviation","team_2_name","team_1_name","winning_name","boxscore"], inplace=True)


In [73]:
# Remove categorical data

df3.drop(columns=["year","week","home_score","away_score"], inplace=True)

C:\Users\dariu\AppData\Local\Temp\ipykernel_20400\659904871.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.drop(columns=["year","week","home_score","away_score"], inplace=True)


In [82]:
# Create target and features

y = df3["home_win"]
X = df3.drop(columns="home_win")

In [75]:
# Apply Train_Test_Split

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1)

In [76]:
# Set the scaler
scaler = StandardScaler()

In [77]:
# Fit and Transform the data
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [171]:
# Create the model
model = RandomForestClassifier()

In [172]:
# Fit the data
model.fit(X_train,y_train)

RandomForestClassifier()

In [173]:
# Make the predictions
y_pred = model.predict(X_test)

In [81]:
# print the results

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[140 158]
 [146 238]]
              precision    recall  f1-score   support

          -1       0.49      0.47      0.48       298
           1       0.60      0.62      0.61       384

    accuracy                           0.55       682
   macro avg       0.55      0.54      0.54       682
weighted avg       0.55      0.55      0.55       682

0.5542521994134897


In [101]:
importances_names = model.feature_names_in_

In [174]:
#importances = model.feature_importances_

importances=model.feature_importances_
indices = np.argsort(importances)[::-1]  # index value of a feature
names = [X_train.columns[i] for i in indices]  # extract the title of that feature

In [176]:
names[:10]

['team_2_percent_drives_with_points',
 'team_1_yards_from_penalties',
 'team_2_rank',
 'team_2_simple_rating_system',
 'team_2_first_downs',
 'team_1_percent_drives_with_points',
 'team_1_rush_attempts',
 'team_1_plays',
 'team_1_rush_first_downs',
 'team_2_points_against']

In [103]:
importances_df = pd.DataFrame(importances,importances_names)

In [180]:
importances_df.sort_values(ascending = False, by = [0]).head(50)

0
team_2_percent_drives_with_points      0.022416
team_2_plays                           0.019592
team_1_yards_from_penalties            0.019142
team_2_yards_from_penalties            0.018916
team_2_points_contributed_by_offense   0.018612
team_2_rank                            0.018239
team_2_pass_net_yards_per_attempt      0.018175
team_2_strength_of_schedule            0.017747
team_1_rank                            0.017559
team_2_first_downs                     0.017551
team_2_points_for                      0.017449
team_2_simple_rating_system            0.017379
team_1_percent_drives_with_points      0.017127
team_1_rush_first_downs                0.017098
team_2_margin_of_victory               0.016952
team_1_plays                           0.016614
team_2_pass_attempts                   0.016555
team_2_percent_drives_with_turnovers   0.016476
team_2_offensive_simple_rating_system  0.016430
team_1_rush_yards                      0.016428
team_2_points_against                  0.016358
team_1_rush_attempts                   0.016224
team_2_yards                           0.016151
team_2_rush_first_downs                0.015983
team_2_rush_attempts                   0.015890
team_1_percent_drives_with_turnovers   0.015612
team_2_pass_yards                      0.015586
team_2_rush_yards                      0.015307
team_2_defensive_simple_rating_system  0.015259
team_2_points_difference               0.015179
team_2_yards_per_play                  0.015028
team_1_penalties                       0.014750
team_2_penalties                       0.014579
team_1_pass_net_yards_per_attempt      0.014559
team_1_points_against                  0.014518
team_2_pass_completions                0.014493
team_2_first_downs_from_penalties      0.014479
team_2_rush_yards_per_attempt          0.014200
team_1_simple_rating_system            0.014175
team_1_margin_of_victory               0.013874
team_1_offensive_simple_rating_system  0.013756
team_2_pass_first_downs                0.013559
team_2_turnovers                       0.013513
team_1_pass_yards                      0.013484
team_1_points_for                      0.013391
team_1_pass_completions                0.013342
team_1_points_contributed_by_offense   0.013108
team_1_first_downs                     0.012951
team_1_strength_of_schedule            0.012889
team_1_first_downs_from_penalties      0.012829

In [118]:
importances_df.describe()

0
count  74.000000
mean    0.013514
std     0.004308
min     0.000000
25%     0.012109
50%     0.014340
75%     0.016430
max     0.022416

In [119]:
df4 = df3.drop(columns=["team_1_games_played","team_2_games_played","team_2_losses","team_1_wins","team_2_wins","team_1_losses"])

In [120]:
df4

team_1_defensive_simple_rating_system  team_1_first_downs  \
0                                      -7.1                  59   
1                                       2.1                  43   
2                                     -13.6                  74   
3                                       1.6                  63   
4                                      -8.0                  52   
...                                     ...                 ...   
2733                                   -9.9                  69   
2734                                   -8.2                  56   
2735                                   10.8                  50   
2736                                    4.5                  54   
2737                                   -7.1                  59   

      team_1_first_downs_from_penalties  team_1_fumbles  team_1_interceptions  \
0                                     7               1                     2   
1                                     5               0                     4   
2                                     7               0                     1   
3                                     5               0                     2   
4                                     8               1                     2   
...                                 ...             ...                   ...   
2733                                  4               0                     1   
2734                                  8               2                     3   
2735                                  7               3                     1   
2736                                  7               2                     1   
2737                                  7               1                     2   

      team_1_margin_of_victory  team_1_offensive_simple_rating_system  \
0                         -1.0                                   -3.3   
1                         -1.7                                   -4.0   
2                          4.3                                    9.9   
3                          0.7                                   28.5   
4                         -3.3                                    0.1   
...                        ...                                    ...   
2733                      -8.3                                   -9.4   
2734                      -7.7                                   -7.5   
2735                       8.0                                   -2.8   
2736                       2.3                                  -11.8   
2737                      -1.0                                   -3.3   

      team_1_pass_attempts  team_1_pass_completions  team_1_pass_first_downs  \
0                       92                       59                       23   
1                       45                       23                       11   
2                       92                       61                       34   
3                      112                       66                       38   
4                      107                       62                       27   
...                    ...                      ...                      ...   
2733                   145                       92                       40   
2734                   103                       79                       34   
2735                   103                       67                       32   
2736                   106                       63                       32   
2737                    92                       59                       23   

      ...  team_2_rush_yards  team_2_rush_yards_per_attempt  \
0     ...                354                            4.7   
1     ...                313                            4.0   
2     ...                451                            4.4   
3     ...                217                            3.4   
4     ...                192                            3.3   
...   ...   

In [121]:
y = df4["home_win"]
X = df4.drop(columns="home_win")

In [122]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1)

In [123]:
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [124]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [125]:
y_pred = model.predict(X_test)

In [126]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[133 165]
 [143 241]]
              precision    recall  f1-score   support

          -1       0.48      0.45      0.46       298
           1       0.59      0.63      0.61       384

    accuracy                           0.55       682
   macro avg       0.54      0.54      0.54       682
weighted avg       0.54      0.55      0.55       682

0.5483870967741935


In [127]:
from sklearn.preprocessing import MinMaxScaler

In [128]:
scaler = MinMaxScaler()

In [129]:
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [130]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [137]:
y_pred = model.predict(X_test)

In [132]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[142 156]
 [140 244]]
              precision    recall  f1-score   support

          -1       0.50      0.48      0.49       298
           1       0.61      0.64      0.62       384

    accuracy                           0.57       682
   macro avg       0.56      0.56      0.56       682
weighted avg       0.56      0.57      0.56       682

0.5659824046920822


In [133]:
from sklearn.preprocessing import RobustScaler

In [134]:
scaler = RobustScaler()

In [135]:
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [136]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [138]:
y_pred = model.predict(X_test)

In [139]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[139 159]
 [139 245]]
              precision    recall  f1-score   support

          -1       0.50      0.47      0.48       298
           1       0.61      0.64      0.62       384

    accuracy                           0.56       682
   macro avg       0.55      0.55      0.55       682
weighted avg       0.56      0.56      0.56       682

0.5630498533724341


In [140]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1, test_size=.3)

In [141]:
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [142]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [143]:
y_pred = model.predict(X_test)

In [144]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[167 196]
 [165 291]]
              precision    recall  f1-score   support

          -1       0.50      0.46      0.48       363
           1       0.60      0.64      0.62       456

    accuracy                           0.56       819
   macro avg       0.55      0.55      0.55       819
weighted avg       0.56      0.56      0.56       819

0.5592185592185592


In [146]:
from sklearn.preprocessing import MaxAbsScaler

In [147]:
scaler = MaxAbsScaler()

In [148]:
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [149]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [150]:
y_pred = model.predict(X_test)

In [151]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[154 209]
 [164 292]]
              precision    recall  f1-score   support

          -1       0.48      0.42      0.45       363
           1       0.58      0.64      0.61       456

    accuracy                           0.54       819
   macro avg       0.53      0.53      0.53       819
weighted avg       0.54      0.54      0.54       819

0.5445665445665445


In [155]:
!pip install xgboost

     -------------------------------------- 125.4/125.4 MB 4.6 MB/s eta 0:00:00


In [156]:
import xgboost as xgb

In [157]:
from xgboost import XGBClassifier

In [158]:
model = XGBClassifier()

In [159]:
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [160]:
model.fit(X_train,y_train)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1], got [-1  1]

In [183]:
df4["home_win"].value_counts()

 1    1520
-1    1207
Name: home_win, dtype: int64

In [166]:
from imblearn.over_sampling import SMOTE

In [167]:
from collections import Counter

In [169]:
sm = SMOTE(df4)


C:\Users\dariu\anaconda3\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=      team_1_defensive_simple_rating_system  team_1_first_downs  \
0                                      -7.1                  59   
1                                       2.1                  43   
2                                     -13.6                  74   
3                                       1.6                  63   
4                                      -8.0                  52   
...                                     ...                 ...   
2733                                   -9.9                  69   
2734                                   -8.2                  56   
2735                                   10.8                  50   
2736                                    4.5                  54   
2737                                   -7.1                  59   

      team_1_first_downs_from_penalties  team_1_fumbles  team_1_interceptions  